// File generated by FlutterFire CLI.
// PLACEHOLDER — Run `flutterfire configure` to replace this file with real values,
// or manually fill in the values from your Firebase Console project settings.
//
// How to get real values:
// 1. Go to https://console.firebase.google.com
// 2. Create a project (or use existing one)
// 3. Add an Android app with package name: com.prm393.smart_task_management
// 4. Download google-services.json → place in android/app/
// 5. Run: dart pub global activate flutterfire_cli
//         flutterfire configure
// That command will auto-regenerate this file with correct values.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── REPLACE all placeholder values below with your real Firebase config ───
  // Get these from: Firebase Console → Project Settings → Your apps

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDayNejkJb6ZRVjGnX-OhlCU22L-zbNE-c',
    appId: '1:733019613648:android:dba8e9345e9586fe40f1d5',
    messagingSenderId: '733019613648',
    projectId: 'prm393-group5',
    storageBucket: 'prm393-group5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-IXuACmARvjI32jTmJPDcsL3SzxaHNs',
    appId: '1:733019613648:ios:96223fdcd789ca2d40f1d5',
    messagingSenderId: '733019613648',
    projectId: 'prm393-group5',
    storageBucket: 'prm393-group5.firebasestorage.app',
    iosBundleId: 'com.prm393.smartTaskManagement',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkijziHbQS45I8JjSpZDp83FYvrayDg0U',
    appId: '1:733019613648:web:d4671e7e692d88d240f1d5',
    messagingSenderId: '733019613648',
    projectId: 'prm393-group5',
    authDomain: 'prm393-group5.firebaseapp.com',
    storageBucket: 'prm393-group5.firebasestorage.app',
    measurementId: 'G-6608L9EXZE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6-IXuACmARvjI32jTmJPDcsL3SzxaHNs',
    appId: '1:733019613648:ios:96223fdcd789ca2d40f1d5',
    messagingSenderId: '733019613648',
    projectId: 'prm393-group5',
    storageBucket: 'prm393-group5.firebasestorage.app',
    iosBundleId: 'com.prm393.smartTaskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkijziHbQS45I8JjSpZDp83FYvrayDg0U',
    appId: '1:733019613648:web:a52a741b44bd3d1d40f1d5',
    messagingSenderId: '733019613648',
    projectId: 'prm393-group5',
    authDomain: 'prm393-group5.firebaseapp.com',
    storageBucket: 'prm393-group5.firebasestorage.app',
    measurementId: 'G-DPKGVK3FCV',
  );
}
